### ISSUE TITLE
Problem starting the server

### ISSUE THREAD

**Issue by CallMeAndre2910** [CreeperMagnet/the-creepers-code#163]
Hi, I have a problem. Putting the datapack in my server, after starting it it closes after few seconds. Here's what it tells me:

[15:51:53 INFO]: Found new data pack file/datapacks.zip, loading it automatically
[15:51:53 WARN]: ResourcePack: ignored non-lowercase namespace: .DS_Store in ./world/datapacks/Magic-Wands-Data-Pack-1.19.1.zip
[15:51:53 WARN]: ResourcePack: ignored non-lowercase namespace: .DS_Store in ./world/datapacks/Magic-Wands-Data-Pack-1.19.1.zip
[15:51:55 WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: com.google.gson.JsonParseException: Error loading registry data: No key name in MapLike[{"elements":[{"element":{"element_type":"minecraft:single_pool_element","location":"tcc:woodland_mansion/main","processors":"minecraft:empty","projection":"rigid"},"weight":1}],"fallback":"minecraft:empty"}]
at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
at net.minecraft.server.Main.main(Main.java:268) ~[paper-1.19.2.jar:git-Paper-307]
at org.bukkit.craftbukkit.Main.main(Main.java:302) ~[paper-1.19.2.jar:git-Paper-307]
at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.JsonParseException: Error loading registry data: No key name in MapLike[{"elements":[{"element":{"element_type":"minecraft:single_pool_element","location":"tcc:woodland_mansion/main","processors":"minecraft:empty","projection":"rigid"},"weight":1}],"fallback":"minecraft:empty"}]
at net.minecraft.core.RegistryAccess.lambda$readRegistry$13(RegistryAccess.java:212) ~[?:?]
at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
at net.minecraft.core.RegistryAccess.lambda$readRegistry$13(RegistryAccess.java:212) ~[?:?]
at net.minecraft.core.RegistryAccess.load(RegistryAccess.java:205) ~[?:?]
at net.minecraft.resources.RegistryOps.createAndLoad(RegistryOps.java:30) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.resources.RegistryOps.createAndLoad(RegistryOps.java:24) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.Main.lambda$main$0(Main.java:237) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.WorldLoader.load(WorldLoader.java:22) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.WorldStem.dataPackResources(WorldStem.java:11) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.server.Main.lambda$main$1(Main.java:235) ~[paper-1.19.2.jar:git-Paper-307]
at net.minecraft.Util.blockUntilDone(Util.java:818) ~[?:?]
at net.minecraft.Util.blockUntilDone(Util.java:813) ~[?:?]
at net.minecraft.server.Main.main(Main.java:234) ~[paper-1.19.2.jar:git-Paper-307]
... 3 more

**Comment by CreeperMagnet** [comment]
Crazy how your log says "paper 1.19.2" there when the download page says specifically not to use paper and to use 1.19.4.
