### ISSUE TITLE
Server not starting, crashing immediately when i open the file

### ISSUE THREAD

**Issue by DeeepFriedWatrr** [CreeperMagnet/the-creepers-code#164]
log:

[14:59:15] [ServerMain/WARN]: Failed to add PDH Counter: \Paging File(_Total)\% Usage, Error code: 0xC0000BB8
[14:59:15] [ServerMain/WARN]: Failed to add counter for PDH counter: \Paging File(_Total)\% Usage
[14:59:15] [ServerMain/WARN]: Disabling further attempts to query Paging File.
[14:59:16] [ServerMain/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[14:59:18] [ServerMain/INFO]: Building unoptimized datafixer
[14:59:19] [ServerMain/WARN]: You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.
[14:59:19] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:59:20] [ServerMain/INFO]: Found new data pack file/datapacks.zip, loading it automatically
[14:59:20] [ServerMain/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: com.google.gson.JsonParseException: Error loading registry data: No key name in MapLike[{"elements":[{"element":{"element_type":"minecraft:single_pool_element","location":"tcc:village_mangrove_swamp/town_centers/tree","processors":"minecraft:empty","projection":"rigid"},"weight":150},{"element":{"element_type":"minecraft:single_pool_element","location":"tcc:village_mangrove_swamp/town_centers/fountain","processors":"minecraft:empty","projection":"rigid"},"weight":50},{"element":{"element_type":"minecraft:single_pool_element","location":"tcc:village_mangrove_swamp/town_centers/gate","processors":"minecraft:empty","projection":"rigid"},"weight":50},{"element":{"element_type":"minecraft:single_pool_element","location":"tcc:village_mangrove_swamp/zombie/town_centers/tree","processors":"tcc:village_mangrove_swamp/zombie","projection":"rigid"},"weight":3},{"element":{"element_type":"minecraft:single_pool_element","location":"tcc:village_mangrove_swamp/zombie/town_centers/fountain","processors":"tcc:village_mangrove_swamp/zombie","projection":"rigid"},"weight":1},{"element":{"element_type":"minecraft:single_pool_element","location":"tcc:village_mangrove_swamp/zombie/town_centers/gate","processors":"tcc:village_mangrove_swamp/zombie","projection":"rigid"},"weight":1}],"fallback":"minecraft:empty"}]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(SourceFile:194) ~[server-1.19.2.jar:?]
	at net.minecraft.bundler.Main.lambda$run$0(Main.java:54) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) [?:?]
Caused by: com.google.gson.JsonParseException: Error loading registry data: No key name in MapLike[{"elements":[{"element":{"element_type":"minecraft:single_pool_element","location":"tcc:village_mangrove_swamp/town_centers/tree","processors":"minecraft:empty","projection":"rigid"},"weight":150},{"element":{"element_type":"minecraft:single_pool_element","location":"tcc:village_mangrove_swamp/town_centers/fountain","processors":"minecraft:empty","projection":"rigid"},"weight":50},{"element":{"element_type":"minecraft:single_pool_element","location":"tcc:village_mangrove_swamp/town_centers/gate","processors":"minecraft:empty","projection":"rigid"},"weight":50},{"element":{"element_type":"minecraft:single_pool_element","location":"tcc:village_mangrove_swamp/zombie/town_centers/tree","processors":"tcc:village_mangrove_swamp/zombie","projection":"rigid"},"weight":3},{"element":{"element_type":"minecraft:single_pool_element","location":"tcc:village_mangrove_swamp/zombie/town_centers/fountain","processors":"tcc:village_mangrove_swamp/zombie","projection":"rigid"},"weight":1},{"element":{"element_type":"minecraft:single_pool_element","location":"tcc:village_mangrove_swamp/zombie/town_centers/gate","processors":"tcc:village_mangrove_swamp/zombie","projection":"rigid"},"weight":1}],"fallback":"minecraft:empty"}]
	at hn.a(SourceFile:298) ~[server-1.19.2.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at hn.a(SourceFile:298) ~[server-1.19.2.jar:?]
	at hn.a(SourceFile:292) ~[server-1.19.2.jar:?]
	at aay.a(SourceFile:32) ~[server-1.19.2.jar:?]
	at aay.a(SourceFile:25) ~[server-1.19.2.jar:?]
	at net.minecraft.server.Main.a(SourceFile:162) ~[server-1.19.2.jar:?]
	at abt.a(SourceFile:24) ~[server-1.19.2.jar:?]
	at abu.a(SourceFile:18) ~[server-1.19.2.jar:?]
	at net.minecraft.server.Main.a(SourceFile:158) ~[server-1.19.2.jar:?]
	at ad.a(SourceFile:952) ~[server-1.19.2.jar:?]
	at ad.b(SourceFile:946) ~[server-1.19.2.jar:?]
	at net.minecraft.server.Main.main(SourceFile:156) ~[server-1.19.2.jar:?]
	... 2 more

**Comment by DeeepFriedWatrr** [comment]
nevermind, i did a stupid, i downloaded the wrong one, being 1.19.2, not 1.19.4 sorry for the inconvenience
